/*
 * This source file was generated by the Gradle 'init' task
 */
package io.moonhappy

import kotlin.test.Test
import kotlin.test.assertTrue

class LibraryTest {
    @Test fun someLibraryMethodReturnsTrue() {
        // val classUnderTest = Library()
        // assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'")
        assertTrue(true, "yesy")
    }
}
