/*
 * This source file was generated by the Gradle 'init' task
 */
package io.moonhappy.ipv6mnemonic

import io.moonhappy.ipv6mnemonic.v0_1.Decoder

class Decode {

    fun decode(input: String): ByteArray {
        val decoder = Decoder()
        return decoder.decode(input)
    }

}
