/*
 * This source file was generated by the Gradle 'init' task
 */
package io.moonhappy.ipv6mnemonic.app

import io.moonhappy.ipv6mnemonic.StringUtils

import org.apache.commons.text.WordUtils

fun main() {
    val tokens = StringUtils.split(MessageUtils.getMessage())
    val result = StringUtils.join(tokens)
    println(WordUtils.capitalize(result))
}
